[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "day1"
path = "./src/day1/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
